### ISSUE TITLE
make: Nothing to be done for 'PythonAPI'.

### ISSUE THREAD

**Issue by lylyjy** [rohjunha/multiple-topologies-prediction#2]
Hi, when I run "make PythonAPI" in .carla,
it occurs that:
make: Nothing to be done for 'PythonAPI'.
Can you tell me how to solve it?

The problem occurs when I run python PythonAPI/util/config.py -m Town04 -p 4000,
it occurs that:AttributeError: module 'carla' has no attribute 'Client'

Thanks.

**Comment by rohjunha** [comment]
Hi @lylyjy, can you copy the error message you had?
I am not sure how `make PythonAPI` is running by calling `python PythonAPI/util/config.py`.
(Since we're copying the binary of CARLA, we don't need to build it.)
I found a similar problem from the CARLA repo: https://github.com/carla-simulator/carla/issues/3083.
I am wondering if you run the python command at `$(PROJECT_DIRECTORY)/.carla` and you're using python 3.7 or later.

**Comment by lylyjy** [comment]
When I run python PythonAPI/util/config.py -m Town04 -p 4000,
it occurs that:
Traceback (most recent call last):
  File "PythonAPI/util/config.py", line 288, in <module>
    main()
  File "PythonAPI/util/config.py", line 198, in main
    client = carla.Client(args.host, args.port, worker_threads=1)
AttributeError: module 'carla' has no attribute 'Client'

**Comment by lylyjy** [comment]
I run the python command at $(PROJECT_DIRECTORY)/.carla and you're using python 3.7 or later.

**Comment by rohjunha** [comment]
I think you should run `bash env.sh` before running the python code.
This will add the $(PROJECT_DIRECTORY)/.carla/PythonAPI and egg file into the $PYTHONPATH variable and activate the conda environment.
Sorry for omitting this part in the README. I will update it.
